#!/bin/sh
# tests/sign.sh -- does the identity-key signing chain hold, with no secret and
# no op? A throwaway Ed25519 key stands in for the citizen's; its raw seed is
# extracted and fed to 1f916-seed-to-sshkey.mjs exactly the way op run would
# feed the real one, and 1f916-ssh-sign is driven by git itself.
#
# What is proved: the seed tool's guard refuses a mismatched public key and
# emits nothing; --pubkey-only equals ssh-keygen's own derivation; the PEM it
# emits is a key OpenSSH accepts and that matches the throwaway; the wrapper
# signs a real commit through git, kills its agent, verifies through git, and
# refuses (no signature, non-zero) when the key command refuses.

set -u
HERE=$(cd "$(dirname "$0")/.." && pwd)
TOOL="$HERE/1f916-seed-to-sshkey.mjs"
SIGN="$HERE/1f916-ssh-sign"

for t in node ssh-keygen ssh-agent ssh-add git; do
  command -v "$t" >/dev/null 2>&1 || { printf '# no %s: skipping the signing test\n' "$t"; exit 0; }
done

W=$(mktemp -d) || exit 1
trap 'rm -rf "$W"' EXIT
pass=0; fail=0; n=0
ok()  { n=$((n+1)); pass=$((pass+1)); printf 'ok %d - %s\n' "$n" "$1"; }
nok() { n=$((n+1)); fail=$((fail+1)); printf 'not ok %d - %s\n' "$n" "$1"
        [ $# -gt 1 ] && printf '  # %s\n' "$2"; }

# --- a throwaway key, and its seed the way the vault holds the real one ------
# Generated by node (OpenSSL cannot read OpenSSH-format key files, so ssh-keygen
# is used as the INDEPENDENT check on what the tool emits, not as the source).
node -e '
  const c=require("crypto");
  const {privateKey,publicKey}=c.generateKeyPairSync("ed25519");
  const d=privateKey.export({format:"der",type:"pkcs8"});
  const s=publicKey.export({format:"der",type:"spki"});
  console.log(d.subarray(d.length-32).toString("base64url"));
  console.log(s.subarray(s.length-32).toString("base64url"));' > "$W/kp"
SEED=$(sed -n 1p "$W/kp"); PUB=$(sed -n 2p "$W/kp")
WRONG_PUB=$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64url"))')

# --- 1. the seed tool ---------------------------------------------------------
out=$(EXPECT_PUB="$WRONG_PUB" ED25519_PRIV="$SEED" node "$TOOL" --private-pem 2>/dev/null); rc=$?
if [ "$rc" = 2 ] && [ -z "$out" ]; then ok "1. guard: a seed that does not reproduce EXPECT_PUB -> exit 2, nothing emitted"
else nok "1. guard: a seed that does not reproduce EXPECT_PUB -> exit 2, nothing emitted" "rc=$rc bytes=${#out}"; fi

out=$(EXPECT_PUB="$PUB" node "$TOOL" --private-pem 2>/dev/null); rc=$?
if [ "$rc" = 3 ] && [ -z "$out" ]; then ok "1. no ED25519_PRIV in the environment -> exit 3, nothing emitted"
else nok "1. no ED25519_PRIV in the environment -> exit 3, nothing emitted" "rc=$rc"; fi

EXPECT_PUB="$PUB" ED25519_PRIV="$SEED" node "$TOOL" --private-pem > "$W/pem" 2>/dev/null
chmod 600 "$W/pem"
if ssh-keygen -yf "$W/pem" > "$W/k.pub" 2>/dev/null; then ok "1. the emitted PEM is a private key OpenSSH accepts"
else nok "1. the emitted PEM is a private key OpenSSH accepts"; : > "$W/k.pub"; fi
if grep -q -- '^-----BEGIN OPENSSH PRIVATE KEY-----$' "$W/pem"; then ok "1. and it is armored as OpenSSH expects"
else nok "1. and it is armored as OpenSSH expects"; fi

EXPECT_PUB="$PUB" node "$TOOL" --pubkey-only > "$W/derived.pub" 2>/dev/null
if [ -s "$W/k.pub" ] && [ "$(cut -d' ' -f1,2 "$W/derived.pub")" = "$(cut -d' ' -f1,2 "$W/k.pub")" ]
then ok "1. --pubkey-only (from x alone) equals ssh-keygen -y's derivation from the private key"
else nok "1. --pubkey-only (from x alone) equals ssh-keygen -y's derivation from the private key"; fi

# --- 2. the wrapper, driven by git --------------------------------------------
# The config points SIGN_KEY_CMD at the seed tool WITHOUT op: the seed is put in
# the environment of the key command directly, which is what op run would do.
CONF="$W/sign.conf"
cat > "$CONF" <<EOF
SIGN_KEY_CMD="EXPECT_PUB='$PUB' ED25519_PRIV='$SEED' node '$TOOL' --private-pem"
EOF
printf 'tester@example.org %s\n' "$(cut -d' ' -f1,2 "$W/k.pub")" > "$W/allowed"

git init -q "$W/repo" && cd "$W/repo" || exit 1
git config user.name tester; git config user.email tester@example.org
git config gpg.format ssh
git config gpg.ssh.program "$SIGN"
git config gpg.ssh.allowedSignersFile "$W/allowed"
git config user.signingkey "key::$(cut -d' ' -f1,2 "$W/k.pub")"

# Live agents only: a killed agent can linger as a zombie where nothing reaps
# it (seen in a sandbox), and a zombie holds no key and answers no socket.
live_agents() { ps -axo stat=,comm= 2>/dev/null | awk '$1 !~ /^Z/ && $2 ~ /ssh-agent$/' | wc -l | tr -d ' '; }
agents_before=$(live_agents)
if SSH_SIGN_CONF="$CONF" git commit -q --allow-empty -S -m signed 2>"$W/err"
then ok "2. git commit -S succeeds through the wrapper"
else nok "2. git commit -S succeeds through the wrapper" "$(head -3 "$W/err" | tr '\n' ' ')"; fi
if git cat-file commit HEAD | grep -q 'BEGIN SSH SIGNATURE'; then ok "2. the commit object carries an SSH signature"
else nok "2. the commit object carries an SSH signature"; fi
if SSH_SIGN_CONF="$CONF" git log -1 --show-signature 2>&1 | grep -q 'Good "git" signature'
then ok "2. git verifies it against the allowed signers (verify verbs pass straight through)"
else nok "2. git verifies it against the allowed signers (verify verbs pass straight through)"; fi
sleep 1
agents_after=$(live_agents)
if [ "$agents_after" -le "$agents_before" ]; then ok "2. no ssh-agent outlives the signature"
else nok "2. no ssh-agent outlives the signature" "before=$agents_before after=$agents_after"; fi

# --- 3. refusal is a failed commit, not an unsigned one -------------------------
cat > "$CONF" <<EOF
SIGN_KEY_CMD="EXPECT_PUB='$WRONG_PUB' ED25519_PRIV='$SEED' node '$TOOL' --private-pem"
EOF
head_before=$(git rev-parse HEAD)
if SSH_SIGN_CONF="$CONF" git commit -q --allow-empty -S -m refused 2>/dev/null
then nok "3. a refusing key command yields NO commit" "commit went through"
else ok "3. a refusing key command yields NO commit"; fi
if [ "$(git rev-parse HEAD)" = "$head_before" ]; then ok "3. and HEAD did not move"
else nok "3. and HEAD did not move"; fi

if SSH_SIGN_CONF="$W/nonexistent" git commit -q --allow-empty -S -m noconf 2>/dev/null
then nok "3. no config -> no commit" "commit went through"
else ok "3. no config -> no commit"; fi

printf '# %d tests, %d passed, %d failed\n' "$n" "$pass" "$fail"
[ "$fail" = 0 ] || exit 1
